# Generated by Django 6.0.2 on 2026-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_traveled_toeurope', models.BooleanField(default=False)),
                ('contries', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
